spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3307/identity_service}
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  valid-duration: 7200 # in second
  refreshable-duration: 72000 # in seconds
