spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://root:TAvCJEjFpOUMNcDyRXiSgDCHfzurBhXf@junction.proxy.rlwy.net:45886/railway}
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:TAvCJEjFpOUMNcDyRXiSgDCHfzurBhXf}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  valid-duration: 7200 # in second
  refreshable-duration: 72000 # in seconds
