name: Build & Deploy Spring Boot Application

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Spring Boot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the Application
        run: mvn clean package --file pom.xml

      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: thminh101002/identity-service:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: thminh101002
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: thminh101002/identity-service:latest
